
services:
  application:
    build:
      context: .
    container_name: alg-ipo
    restart: unless-stopped
    command: uvicorn src.main.app:application --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app

    ports:
      - "8000:8000"

    env_file:
      - ./.env
